config/routes.rb
Rails.application.routes.draw do
  get 'cliente/index'

  resources :colonias
  get 'socios/index'

  get 'dashboard/index'

  resources :direcciones
  resources :delegaciones
  resources :ciudades
  root 'principal#index'

  devise_for :users, :controllers => { :registrations => "registrations", :sessions =>"sessions" }  # See how all your routes lay out with "rake routes".

  # You can have the root of your site routed with "root"
  # root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/direcciones_controller.rb
class DireccionesController < ApplicationController
  before_action :set_direccion, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :verificar_usuario

  # GET /direcciones
  # GET /direcciones.json
  def index
    @direcciones = Direccion.all
  end

  # GET /direcciones/1
  # GET /direcciones/1.json
  def show
  end

  # GET /direcciones/new
  def new
    @direccion = Direccion.new
  end

  # GET /direcciones/1/edit
  def edit
  end

  # POST /direcciones
  # POST /direcciones.json
  def create
    @direccion = Direccion.new(direccion_params)

    respond_to do |format|
      if @direccion.save
        format.html { redirect_to @direccion, notice: 'Direccion was successfully created.' }
        format.json { render :show, status: :created, location: @direccion }
      else
        format.html { render :new }
        format.json { render json: @direccion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /direcciones/1
  # PATCH/PUT /direcciones/1.json
  def update
    respond_to do |format|
      if @direccion.update(direccion_params)
        format.html { redirect_to @direccion, notice: 'Direccion was successfully updated.' }
        format.json { render :show, status: :ok, location: @direccion }
      else
        format.html { render :edit }
        format.json { render json: @direccion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /direcciones/1
  # DELETE /direcciones/1.json
  def destroy
    @direccion.destroy
    respond_to do |format|
      format.html { redirect_to direcciones_url, notice: 'Direccion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_direccion
      @direccion = Direccion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def direccion_params
      params.require(:direccion).permit(:colonia, :calle, :cp, :delegacion_id)
    end

    def verificar_usuario
      if user_signed_in? && current_user.roles.map(&:name) == ["root"]

      else
        redirect_to root_path, :alert => "No autorizado"
      end
    end

end

app/views/direcciones/_form.html.erb
<%= form_for(@direccion) do |f| %>
  <% if @direccion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@direccion.errors.count, "error") %> prohibited this direccion from being saved:</h2>

      <ul>
      <% @direccion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :colonia %><br>
    <%= f.text_field :colonia %>
  </div>
  <div class="field">
    <%= f.label :calle %><br>
    <%= f.text_field :calle %>
  </div>
  <div class="field">
    <%= f.label :cp %><br>
    <%= f.text_field :cp %>
  </div>
  <div class="field">
    <%= f.label :delegacion_id %><br>
    <%= f.text_field :delegacion_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/direcciones/edit.html.erb
<h1>Editing Direccion</h1>

<%= render 'form' %>

<%= link_to 'Show', @direccion %> |
<%= link_to 'Back', direcciones_path %>

app/views/direcciones/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Direcciones</h1>

<table>
  <thead>
    <tr>
      <th>Colonia</th>
      <th>Calle</th>
      <th>Cp</th>
      <th>Delegacion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @direcciones.each do |direccion| %>
      <tr>
        <td><%= direccion.colonia %></td>
        <td><%= direccion.calle %></td>
        <td><%= direccion.cp %></td>
        <td><%= direccion.delegacion %></td>
        <td><%= link_to 'Show', direccion %></td>
        <td><%= link_to 'Edit', edit_direccion_path(direccion) %></td>
        <td><%= link_to 'Destroy', direccion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Direccion', new_direccion_path %>

app/views/direcciones/new.html.erb
<h1>New Direccion</h1>

<%= render 'form' %>

<%= link_to 'Back', direcciones_path %>

app/views/direcciones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Colonia:</strong>
  <%= @direccion.colonia %>
</p>

<p>
  <strong>Calle:</strong>
  <%= @direccion.calle %>
</p>

<p>
  <strong>Cp:</strong>
  <%= @direccion.cp %>
</p>

<p>
  <strong>Delegacion:</strong>
  <%= @direccion.delegacion %>
</p>

<%= link_to 'Edit', edit_direccion_path(@direccion) %> |
<%= link_to 'Back', direcciones_path %>