config/routes.rb
Rails.application.routes.draw do
  get 'cliente/index'

  resources :colonias
  get 'socios/index'

  get 'dashboard/index'

  resources :direcciones
  resources :delegaciones
  resources :ciudades
  root 'principal#index'

  devise_for :users, :controllers => { :registrations => "registrations", :sessions =>"sessions" }  # See how all your routes lay out with "rake routes".

  # You can have the root of your site routed with "root"
  # root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/delegaciones_controller.rb
class DelegacionesController < ApplicationController
  before_action :set_delegacion, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :verificar_usuario

  # GET /delegaciones
  # GET /delegaciones.json
  def index
    @delegaciones = Delegacion.all
  end

  # GET /delegaciones/1
  # GET /delegaciones/1.json
  def show
  end

  # GET /delegaciones/new
  def new
    @delegacion = Delegacion.new
  end

  # GET /delegaciones/1/edit
  def edit
  end

  # POST /delegaciones
  # POST /delegaciones.json
  def create
    @delegacion = Delegacion.new(delegacion_params)

    respond_to do |format|
      if @delegacion.save
        format.html { redirect_to @delegacion, notice: 'Delegacion was successfully created.' }
        format.json { render :show, status: :created, location: @delegacion }
      else
        format.html { render :new }
        format.json { render json: @delegacion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /delegaciones/1
  # PATCH/PUT /delegaciones/1.json
  def update
    respond_to do |format|
      if @delegacion.update(delegacion_params)
        format.html { redirect_to @delegacion, notice: 'Delegacion was successfully updated.' }
        format.json { render :show, status: :ok, location: @delegacion }
      else
        format.html { render :edit }
        format.json { render json: @delegacion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /delegaciones/1
  # DELETE /delegaciones/1.json
  def destroy
    @delegacion.destroy
    respond_to do |format|
      format.html { redirect_to delegaciones_url, notice: 'Delegacion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_delegacion
      @delegacion = Delegacion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def delegacion_params
      params.require(:delegacion).permit(:ciudad_id, :nombre)
    end

    def verificar_usuario
      if user_signed_in? && current_user.roles.map(&:name) == ["root"]

      else
        redirect_to root_path, :alert => "No autorizado"
      end
    end

end

app/views/delegaciones/_form.html.erb
<%= form_for(@delegacion) do |f| %>
  <% if @delegacion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@delegacion.errors.count, "error") %> prohibited this delegacion from being saved:</h2>

      <ul>
      <% @delegacion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ciudad_id %><br>
    <%= f.text_field :ciudad_id %>
  </div>
  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/delegaciones/edit.html.erb
<h1>Editing Delegacion</h1>

<%= render 'form' %>

<%= link_to 'Show', @delegacion %> |
<%= link_to 'Back', delegaciones_path %>

app/views/delegaciones/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Delegaciones</h1>

<table>
  <thead>
    <tr>
      <th>Ciudad</th>
      <th>Nombre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @delegaciones.each do |delegacion| %>
      <tr>
        <td><%= delegacion.ciudad %></td>
        <td><%= delegacion.nombre %></td>
        <td><%= link_to 'Show', delegacion %></td>
        <td><%= link_to 'Edit', edit_delegacion_path(delegacion) %></td>
        <td><%= link_to 'Destroy', delegacion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Delegacion', new_delegacion_path %>

app/views/delegaciones/new.html.erb
<h1>New Delegacion</h1>

<%= render 'form' %>

<%= link_to 'Back', delegaciones_path %>

app/views/delegaciones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ciudad:</strong>
  <%= @delegacion.ciudad %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @delegacion.nombre %>
</p>

<%= link_to 'Edit', edit_delegacion_path(@delegacion) %> |
<%= link_to 'Back', delegaciones_path %>