config/routes.rb
Rails.application.routes.draw do
  get 'cliente/index'

  resources :colonias
  get 'socios/index'

  get 'dashboard/index'

  resources :direcciones
  resources :delegaciones
  resources :ciudades
  root 'principal#index'

  devise_for :users, :controllers => { :registrations => "registrations", :sessions =>"sessions" }  # See how all your routes lay out with "rake routes".

  # You can have the root of your site routed with "root"
  # root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/ciudades_controller.rb
class CiudadesController < ApplicationController
  before_action :set_ciudad, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!
    before_action :verificar_usuario

  # GET /ciudades
  # GET /ciudades.json
  def index
    @ciudades = Ciudad.all
  end

  # GET /ciudades/1
  # GET /ciudades/1.json
  def show
  end

  # GET /ciudades/new
  def new
    @ciudad = Ciudad.new
  end

  # GET /ciudades/1/edit
  def edit
  end

  # POST /ciudades
  # POST /ciudades.json
  def create
    @ciudad = Ciudad.new(ciudad_params)

    respond_to do |format|
      if @ciudad.save
        format.html { redirect_to @ciudad, notice: 'Ciudad was successfully created.' }
        format.json { render :show, status: :created, location: @ciudad }
      else
        format.html { render :new }
        format.json { render json: @ciudad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ciudades/1
  # PATCH/PUT /ciudades/1.json
  def update
    respond_to do |format|
      if @ciudad.update(ciudad_params)
        format.html { redirect_to @ciudad, notice: 'Ciudad was successfully updated.' }
        format.json { render :show, status: :ok, location: @ciudad }
      else
        format.html { render :edit }
        format.json { render json: @ciudad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ciudades/1
  # DELETE /ciudades/1.json
  def destroy
    @ciudad.destroy
    respond_to do |format|
      format.html { redirect_to ciudades_url, notice: 'Ciudad was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ciudad
      @ciudad = Ciudad.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ciudad_params
      params.require(:ciudad).permit(:nombre)
    end

    def verificar_usuario
      if user_signed_in? && current_user.roles.map(&:name) == ["root"]

      else
        redirect_to root_path, :alert => "No autorizado"
      end
    end


end

app/views/ciudades/_form.html.erb
<%= form_for(@ciudad) do |f| %>
  <% if @ciudad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ciudad.errors.count, "error") %> prohibited this ciudad from being saved:</h2>

      <ul>
      <% @ciudad.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ciudades/edit.html.erb
<h1>Editing Ciudad</h1>

<%= render 'form' %>

<%= link_to 'Show', @ciudad %> |
<%= link_to 'Back', ciudades_path %>

app/views/ciudades/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Ciudades</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ciudades.each do |ciudad| %>
      <tr>
        <td><%= ciudad.nombre %></td>
        <td><%= link_to 'Show', ciudad %></td>
        <td><%= link_to 'Edit', edit_ciudad_path(ciudad) %></td>
        <td><%= link_to 'Destroy', ciudad, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ciudad', new_ciudad_path %>

app/views/ciudades/new.html.erb
<h1>New Ciudad</h1>

<%= render 'form' %>

<%= link_to 'Back', ciudades_path %>

app/views/ciudades/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @ciudad.nombre %>
</p>

<%= link_to 'Edit', edit_ciudad_path(@ciudad) %> |
<%= link_to 'Back', ciudades_path %>