config/routes.rb
Rails.application.routes.draw do
  get 'cliente/index'

  resources :colonias
  get 'socios/index'

  get 'dashboard/index'

  resources :direcciones
  resources :delegaciones
  resources :ciudades
  root 'principal#index'

  devise_for :users, :controllers => { :registrations => "registrations", :sessions =>"sessions" }  # See how all your routes lay out with "rake routes".

  # You can have the root of your site routed with "root"
  # root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/colonia.rb
class Colonia < ActiveRecord::Base
  belongs_to :ciudad
  has_many :coloniacoberturas
end

app/controllers/colonias_controller.rb
class ColoniasController < ApplicationController
  before_action :set_colonia, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :verificar_usuario

  # GET /colonias
  # GET /colonias.json
  def index
    @colonias = Colonia.all
  end

  # GET /colonias/1
  # GET /colonias/1.json
  def show
  end

  # GET /colonias/new
  def new
    @colonia = Colonia.new
  end

  # GET /colonias/1/edit
  def edit
  end

  # POST /colonias
  # POST /colonias.json
  def create
    @colonia = Colonia.new(colonia_params)

    respond_to do |format|
      if @colonia.save
        format.html { redirect_to @colonia, notice: 'Colonia was successfully created.' }
        format.json { render :show, status: :created, location: @colonia }
      else
        format.html { render :new }
        format.json { render json: @colonia.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /colonias/1
  # PATCH/PUT /colonias/1.json
  def update
    respond_to do |format|
      if @colonia.update(colonia_params)
        format.html { redirect_to @colonia, notice: 'Colonia was successfully updated.' }
        format.json { render :show, status: :ok, location: @colonia }
      else
        format.html { render :edit }
        format.json { render json: @colonia.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /colonias/1
  # DELETE /colonias/1.json
  def destroy
    @colonia.destroy
    respond_to do |format|
      format.html { redirect_to colonias_url, notice: 'Colonia was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_colonia
      @colonia = Colonia.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def colonia_params
      params.require(:colonia).permit(:nombre, :ciudad_id)
    end

    def verificar_usuario
      if user_signed_in? && current_user.roles.map(&:name) == ["Socia"]

      else
        redirect_to root_path, :alert => "No autorizado"
      end
    end

end

app/views/colonias/_form.html.erb
<%= form_for(@colonia) do |f| %>
  <% if @colonia.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@colonia.errors.count, "error") %> prohibited this colonia from being saved:</h2>

      <ul>
      <% @colonia.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :ciudad_id %><br>
    <%= f.text_field :ciudad_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/colonias/edit.html.erb
<h1>Editing Colonia</h1>

<%= render 'form' %>

<%= link_to 'Show', @colonia %> |
<%= link_to 'Back', colonias_path %>

app/views/colonias/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Colonias</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Ciudad</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @colonias.each do |colonia| %>
      <tr>
        <td><%= colonia.nombre %></td>
        <td><%= colonia.ciudad %></td>
        <td><%= link_to 'Show', colonia %></td>
        <td><%= link_to 'Edit', edit_colonia_path(colonia) %></td>
        <td><%= link_to 'Destroy', colonia, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Colonia', new_colonia_path %>

app/views/colonias/new.html.erb
<h1>New Colonia</h1>

<%= render 'form' %>

<%= link_to 'Back', colonias_path %>

app/views/colonias/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @colonia.nombre %>
</p>

<p>
  <strong>Ciudad:</strong>
  <%= @colonia.ciudad %>
</p>

<%= link_to 'Edit', edit_colonia_path(@colonia) %> |
<%= link_to 'Back', colonias_path %>